@id = 65581e0a328bea4789678b6d
DELETE  http://localhost:3001/api/blogs/{{id}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY1NTgwNmJkZjJiNWQ3ZDM5MjFhMjhmMyIsImlhdCI6MTcwMDQzMTIxOX0.mMW8ZWl2c_69SdDIhds8gbUtM9vWH-KJxLuc3z9Mkj4