POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY1NTgwNmJkZjJiNWQ3ZDM5MjFhMjhmMyIsImlhdCI6MTcwMDQyOTk3Mn0.LH4DB6cVvxm31R02dNDIAErycGJVWGxSlUAj9umJKME

{
  "title": "Test Blog",
  "author": "John Doe",
  "url": "fakedomain.com",
  "likes": 10
}


#

@id=6555741c492f3a275b68c41f
PUT http://localhost:3001/api/blogs/{{id}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY1NTgwNmJkZjJiNWQ3ZDM5MjFhMjhmMyIsImlhdCI6MTcwMDQyOTk3Mn0.LH4DB6cVvxm31R02dNDIAErycGJVWGxSlUAj9umJKME

{
  "title": "UPDATED Test Blog",
  "author": "UPDATED John Doe",
  "url": "updated.com",
  "likes": 13
}