POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "Ensure that everything still works",
  "important": false
}

#

@id=655e8b30c43228e0c319b343
PUT http://localhost:3001/api/notes/{{id}}
Content-Type: application/json

{
  "content": "test after refactor",
  "important": true
}